apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: acme-renew-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/name: {{ .Release.Name | quote }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
subjects:
- kind: ServiceAccount
  name: acme-renew-sa
roleRef:
  kind: Role
  name: acme-renew-role
  apiGroup: rbac.authorization.k8s.io
