apiVersion: v1
kind: Secret
metadata:
  name: acmesh-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/name: {{ .Release.Name | quote }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
stringData:
  # https://github.com/acmesh-official/acme.sh/wiki/dnsapi
  cloudflare-account.conf: |-
    export CF_Token="<CHANGE_YOUR_CF_TOKEN>"
    export CF_Account_ID="<CHANGE_YOUR_CF_ACCOUNT_ID>"
